### ISSUE TITLE
Create corpus from TextGrids

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#172]
create corpus from folder containing TextGrid files, sorting the information in the different tiers into different columns? (along with their acoustic files)

**Comment by kchall** [comment]
@mmcauliffe 
@jsmackie 
Where are we with this one? I don't want to delay 1.0, but it was something a lot of people wanted...

**Comment by mmcauliffe** [comment]
Yeah, the main reason I haven't done anything with this is that no corpora I have use them.  They all use separate word and phone files.  The people behind GECO mentioned they might do a release with TextGrids, but I just don't know what the specifications of input textgrids would be like.  I could model it off of the example textgrid in http://fave.ling.upenn.edu/usingEF.html, or if you have a set a textgrids that you'd like to be able to support, I can get to work on that, too.

**Comment by kchall** [comment]
Just invited you to the CSJ Dropbox folder. @bhallen and @mdfry are also looking into getting that particular corpus up and running, and it's all TextGrids.

**Comment by mmcauliffe** [comment]
Perfect! I'll take a look around it.

**Comment by mmcauliffe** [comment]
@kchall manual/documentation stuff:  We currently inspect textgrids for two kinds of tiers, words and phones.  Word tiers are ones that have some variation of "word" in them, either plural or singular, and with any case (i.e. "Word", "word", "WORD" would all be detected).  Phone tiers are ones that have a variant of "phone", "segment", "transcription" or "seg" in them.  All Point Tiers are ignored, all interval tiers are included as word token attributes (so if there's a tier called "Speech style" and an interval named "casual" extends around the word token, the word token will have an attribute for "Speech style" with the value "casual").  If there are multiple speakers in a text gird, it expects word and phone tiers for each speaker, such as "Speaker 1 - word" and "Speaker 2 - word".

Future direction stuff: The dialog could stand to be more interactive, i.e. users should be able to select which tiers are words/segments, which tiers to include/exclude, etc. Speaker detection for textgrids is kinda screwy at the moment, and really that applies to all spontaneous speech corpora.
