### ISSUE TITLE
Features (?) in IPHOD

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#221]
When creating a new tier for the IPHOD corpus:

1. The segment inventory for the consonants doesn't include [s] or [z].

2. The buttons for [n] and [h] are of a different type than the others.

Looking at the feature system, I don't see anything obvious that would be causing this...

**Comment by mmcauliffe** [comment]
[s] and [z] should appear now, by the by.  I'll have to play around on a mac and see what exactly is causing that weird button issue.  They should all have the same buttons depending only on the OS settings.

**Comment by mmcauliffe** [comment]
This should be all good in the hood!
