### ISSUE TITLE
Edit Feature System

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#222]
1. When using the default IPHOD corpus, there's no indication of the current feature or transcription system given. 

2. Can we do a better job of ordering the segments? Even alphabetical would be better than the current hodgepodge order....

3. Error when selecting "edit segment":
Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/qt/featuregui.py", line 424, in editSegment
    seg = self.table.model().data[selected.row()][0]
TypeError: 'method' object is not subscriptable

**Comment by mmcauliffe** [comment]
Point 1 will be fixed when I regenerate all the default corpora to coincide with the 1.0 release.
