### ISSUE TITLE
Mutual Information

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#226]
1. The dialogue box for adding bigrams is again too large for my laptop screen, and not resizable; with the IPHOD corpus, [s] and [z] do not show up in the inventory, and the buttons for [h] and [n] are different from the others.

2. Selecting a bigram including # doesn't seem to work (results in a pop-up box with a stop sign, but no message other than "#").

**Comment by mmcauliffe** [comment]
I think this is all sorted.  Let me know if more work needs to be done on it.
