### ISSUE TITLE
Add / delete entry

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#231]
Add basic ability to add or delete an entry in the corpus.

**Comment by mmcauliffe** [comment]
Users can add words through a menu item in the Corpus menu.  They minimally have to specify Spelling, Transcription and Frequency.  Tiers will automatically update based on transcription.  Transcription can be typed (and there is error checking for whether segments parsed by '.' are in the corpus' inventory) or entered in by pressing buttons in an inventory window.  There should probably be a warning to regenerate numeric and factor tiers (if they were automatically generated like CV tiers).

**Comment by mmcauliffe** [comment]
Users can remove words by right clicking their entry in the corpus window.  They will be prompted as to whether they are sure.  This will be marked as an unsaved change (regardless of autosave preferences).  Users can also edit word entries by right clicking and selecting the relevant choice, and the dialog is the same as the add word dialog.
