### ISSUE TITLE
PrOD error

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#236]
Using the sample corpus, with a vowel tier created by selecting actual vowel segments (i.e., not features):

-calculate PrOD on the vowel tier
-two pairs: [e, i] and [o, u]
-environments: _[+high], _[-high], _#

-this should be exhaustive and non-overlapping, but the following error occurs: “The following environments for e and i overlapped: 
_[-high], _[‘#’]: #_e, a_a, #_a
_[+high], _[‘#’]: i_i, o_i, e_u, #_u”

(Possible issue: Does [#] have +/- high features?)

**Comment by mmcauliffe** [comment]
It looks to be fixed in the current build, though I didn't do anything overt to fix it.  It may have been fixed when I fixed the issue that Scott was talking about at the meeting, since that's the only time that I would have touched something involving how features work.
