### ISSUE TITLE
Freq. of Alt. / String Similarity

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#237]
Calculating freq. of alt on the sample corpus
Pair: [s], [S]
Algorithm: phonological edit distance 
Threshold: 6
Based on: Transcription
no subset

Error message in GUI is “‘Segment’ object has no attribute ‘values.’”

Possibly related (I didn't notice it until I was closing the session; this may instead have been generated during a string similarity calculation) -- error message in python:

“Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/qt/ssgui.py", line 301, in khorsiSelected
    self.stringTypeWidget.enable()
AttributeError: 'SSDialog' object has no attribute 'stringTypeWidget'”

**Comment by mmcauliffe** [comment]
Should be fixed.
