### ISSUE TITLE
Acoustic similarity bug

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#238]
Acoustic similarity – either for single directory, or two directories – the results seem to be calculated, but table is empty, with the following error:

“Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/qt/asgui.py", line 332, in setResults
    self.representationWidget.name(),
AttributeError: 'RadioSelectWidget' object has no attribute 'name'”

**Comment by mmcauliffe** [comment]
Should be fixed.
