### ISSUE TITLE
Info. about corpus

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#239]
When a corpus is loaded, it used to show the name of the corpus, the number of entries, and the feature system used at the top of the corpus window. Can we re-instate that?

**Comment by mmcauliffe** [comment]
It's sort of there now; along the bottom it says the name of the corpus and the feature system.  I added a menu item in Corpus called "Summary" which should have the number of entries, summaries of the columns (like ranges, means, standard deviations of the numeric columns), and inventory information, but it's not implemented yet.

**Comment by mmcauliffe** [comment]
Corpus summary in the Corpus menu now works in master, though it's somewhat barebones.
