### ISSUE TITLE
Phonological search function

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#242]
When the user searches for an item in the corpus using the "phonological search" function, can we also return both a type and token frequency count?

**Comment by mmcauliffe** [comment]
So at first I thought you meant returning a column with type and token frequency, but that doesn't make too much sense.  Are you thinking like a summary of the frequencies, like summed type and token frequency for the sound in question in the environments specified?  Like Prod results without the actual calculation?

**Comment by kchall** [comment]
Yeah, a column doesn't really work -- I was thinking more like a separate row with the environment and a list of the type and token frequency, or a separate window off to the side of the results table.... So, yes, similar to the PrOD results. Thanks!
