### ISSUE TITLE
PrOD -- Exhaustivity and Uniqueness

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#248]
1. Can we set the default to be to have PCT check for these?
2. Typo in the GUI -- "enviroment" 
3. Update tooltips to reflect that we've combined exhaustivity and uniqueness into a single option, rather than allowing users to pick them independently
4. Reinstate the .txt files containing words missing in non-exhaustive searches and overlapping words in such cases. 
5. Change wording of the exhaustivity error message. e.g. “Exhaustivity is not met. The following environments occur for the pair [i], [e] but are not covered by your environment selections: ....”

**Comment by mmcauliffe** [comment]
@kchall I added an expanded dialog for this, let me know what you think when you get a chance!
