### ISSUE TITLE
Global option for decimal places

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#254]
Allow user to globally specify the number of decimal places (a) to show in GUI tables and (b) to save to file. (The latter is less important if the default is to use all of them.)

**Comment by mmcauliffe** [comment]
The option for changing the number of decimal places for GUI tables is in the "Display" tab of Preferences.  I'm close this for now, since the save the file one is pretty low priority, but feel free to reopen this if you want it in there.
