### ISSUE TITLE
Functional load -- save to file typo

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#257]
Apparently the default file name calls is "funcational" load (though that may be true only in an older version?). (An RA pointed this out to me....)

**Comment by mmcauliffe** [comment]
So I don't know where there would be a file name involving functional load.  Do they mean the save the results file dialog?  That doesn't have any default file name, though maybe it should?

**Comment by kchall** [comment]
Yeah, I assume it was from the dialogue box. But, maybe this is just leftover from the old version; I know we did have several places where default names could be provided before. (The RA was using the packaged version, so it's probably a moot point now.)
