### ISSUE TITLE
Error in sound selection (PrOD?)

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#261]
Using the Gitksan corpus, working with PrOD (though it might happen in other relevant places): When attempting to select the pair of sounds, the following error occurs:

![error_add_pair_of_sounds_prod](https://cloud.githubusercontent.com/assets/7317450/5831425/2e61935a-a0e7-11e4-9635-99a76a18d202.jpg)

I assume this is an error in the feature file. But in the GUI, there should be a more useful error message that pops up to explain the problem (currently nothing happens except in the Python editor interface).

**Comment by mmcauliffe** [comment]
Sure, though that must be using the unmodified version of the Hayes feature system from a long while back.  I'll add some robustness to it though.

**Comment by kchall** [comment]
It's a modified version specifically for the Gitksan corpus, but based on the old Hayes file....
