### ISSUE TITLE
Right click menu for added attributes should do something

### ISSUE THREAD

**Issue by mmcauliffe** [kchall/CorpusTools#291]

**Comment by mmcauliffe** [comment]
@kchall Right clicking on columns gives the option to remove the column, has all the same stuff as going through the Corpus menu, there's a "are you sure" prompt and it enables saving without autosaving.

**Comment by kchall** [comment]
Hmm, this doesn't seem to work on my Mac.

**Comment by mmcauliffe** [comment]
One thing to note is that it only pops up for non default columns, so anything other spelling, transcription or frequency.

**Comment by kchall** [comment]
Ah! Got it. Thanks!
