### ISSUE TITLE
ProD Ex / Uniq errors

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#293]
The new error box and tracking looks great! Two issues:

1. For exhaustivity: the "Open errors directory" button doesn't work (on my Mac);

2. For uniqueness: I get a "name 'overlap_envs" is not defined" error in PCT.

**Comment by mmcauliffe** [comment]
Can you try it again?  I added some code for the open errors directory, but I don't have access to a mac at the moment to test it.  The uniqueness should also be fixed.

Also, the acoustic similarity errors for not finding wav files have this style of error box now, with the details pane listing all the files found in the directory.  It doesn't save to a text file, so there's no open button for them.  Are there any other instances that you can think of that I should do details for?

**Comment by kchall** [comment]
Thanks! First: the "open errors dir" function still doesn't seem to do anything, sorry.

**Comment by kchall** [comment]
Uniqueness now works, too, though has the same issue with opening the errors dir.

I can't think of anywhere else that would need this style of feedback, but I'll let you know. Thanks!

**Comment by mmcauliffe** [comment]
Ok, I pushed another possible fix, so try that?  If it doesn't work, then I'll try to debug it for a bit tomorrow.

**Comment by kchall** [comment]
Will try in a sec. Did notice this error from the last time in case it helps.

Traceback (most recent call last):
  File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/qt/windows.py", line 113, in handleError
    args = ['{}'.format(errordir)]
NameError: name 'errordir' is not defined

**Comment by kchall** [comment]
Nope, sorry, the Linux fix didn't help.

**Comment by mmcauliffe** [comment]
Ok, I'll try to fix it tomorrow before packaging everything.

**Comment by kchall** [comment]
Yep, it works! :)
