### ISSUE TITLE
Acoustic sim. dialogue box

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#296]
The fields where the directory paths should be for a single directory of sound files or pairs of directories is now missing.

![missing_dir_fields](https://cloud.githubusercontent.com/assets/7317450/5995397/cd671890-aa5f-11e4-88a9-df76a65edefa.jpg)

**Comment by mmcauliffe** [comment]
It looks fine on windows, so I'll have to debug it tomorrow.

**Comment by kchall** [comment]
This one is odd, because it used to be fine (my old screen shots show the dir names)!

**Comment by mmcauliffe** [comment]
If you make the window bigger, the boxes don't magically reappear, right?

**Comment by kchall** [comment]
You're so clever! Yes, they do appear if I make the box bigger. Can we set the default size slightly larger? :)

**Comment by mmcauliffe** [comment]
I did a small change to make the text in the options pane about multiprocessing being only available with python-acoustic-similarity smaller, so hopefully they should show up again.  I think it comes from the conflict of your screen size (and the dialog only wanting to take up a certain amount of it) and the mininmum size of the dialog.  I'll play around with other ways of making sure those text boxes don't disappear.
