### ISSUE TITLE
Prompt user to save on exit when there are unsaved changes

### ISSUE THREAD

**Issue by mmcauliffe** [kchall/CorpusTools#297]

**Comment by mmcauliffe** [comment]
@kchall When the user exits with unsaved changes, the window now has options for "Save", "Don't save" and "Cancel", rather than "Continue" and "Abort", so there's no need to abort, manually save and re exit anymore.

**Comment by kchall** [comment]
Cool! Can this also be changed when the user goes to load a new corpus after making changes to an original corpus? Currently, it's the old "abort / continue" box there.
