### ISSUE TITLE
Construct digraph

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#300]
Argh. Just going through what I want to present tomorrow, and discovered this error when trying to create the Gitksan corpus and construct digraphs while loading in the corpus:

![construct_digraph_error](https://cloud.githubusercontent.com/assets/7317450/6014081/fb273586-ab2b-11e4-9bb6-42a89f97892c.jpg)

**Comment by mmcauliffe** [comment]
Whoops, my fix broke something else, but all should be good now.
