### ISSUE TITLE
Allow user to "switch order" of segment pairs

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#317]
In Functional Load and ProD, when a pair of sounds is selected, the first one on the chart is the one that is listed as "segment 1" while the second one on the chart is the one listed as "segment 2." But, if the user wants to "treat all segment pairs together," the order of the pairs really matters. We need to have a way that they can easily swap the order of each pair. (Maybe a little bidirectional arrow next to each one, and clicking on it swaps the order?)

**Comment by mmcauliffe** [comment]
Should be implemented now!  The icon hopefully looks okay on all OSs!

**Comment by kchall** [comment]
Not sure what it's supposed to look like, but here's a screenshot from my Mac. It's usable, and it works, but it's not entirely intuitive. ;-)
![switch_order_button](https://cloud.githubusercontent.com/assets/7317450/6404334/9f3332ae-bdcb-11e4-9c34-fe5328ca500d.jpg)

**Comment by kchall** [comment]
Argh, the images aren't working. Anyway, it's a plain grey square. It's the file called "switch_order_button.jpg" in the Dropbox if you want to see.

**Comment by mmcauliffe** [comment]
Ah, yes, I didn't realize that the way I did it is linux only. For other OSs, I'll have to include an icon file to use with it.

**Comment by mmcauliffe** [comment]
Could you try it again?  There should be a bundled icon available for Windows and Mac now (though I've only tested Windows).

**Comment by kchall** [comment]
Yep, looks good -- thanks!
