### ISSUE TITLE
Wording for homophones in Functional Load

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#334]
In the dialogue box where users input parameters for functional load, there's an option to "include homophones" but the output table lists the parameter as "ignored homophones?" Checking the "include" box leads to the output of "ignored homophones--yes," which makes no sense. So I think the output table column name should be changed to "Included homophones?"

@bhallen does this make sense?

**Comment by bhallen** [comment]
On the back-end, the parameter is called `distinguish_homophones`, which I think is a more accurate description of what the parameter is actually doing. (Ignoring/including sounds too vague to me; see #336.)

So personally, I'd recommend that the GUI and output table both say "distinguish(ed) homophones?".
