### ISSUE TITLE
Problem with minimal pair functional load count?

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#336]
Using the LF_syllables_v2.txt file (which I've put in the "test files" Dropbox folder), calculate functional load of [a], [O] as raw counts of minimal pairs, not including homophones. The total number returned is 7. But there are clearly more than 7 actual minimal pairs, e.g.:

b_f (baffe, bof)
b_g (bague, bogue)
b_k (bac, boc)
b_l (bal, bol)
b_r (barre, bore)
b_s (baes, bosse)
b_t (batte, bote)
n_p (nap, nope)
n_r (nard, nord)
n_t (natte, note)

While some of these words do have homophones (e.g., [nap] occurs in both <nap> and <nappe>), each word should be counted at least ONCE. That is, "ignoring" homophones shouldn't be the same as simply removing ALL homophonic words from the count -- it should be the same as reducing them to 1 instance of each. 

(I'm not 100% sure that this is where the error is coming from, but it's the most obvious thing I can think of....)

**Comment by bhallen** [comment]
Kathleen, could you please send me the LF_syllables_v2.txt file? I had to
leave the Measuring_Phonological_Relationships Dropbox folder because some
temporary space of mine vanished.

**Comment by bhallen** [comment]
There were two small bugs responsible for this, one old and one new. Good catch, Kathleen! Everything should be fixed now.

**Comment by kchall** [comment]
Yikes, thanks for fixing it Blake! Question for everyone and especially @mmcauliffe -- this seems like a serious error, and is presumably packaged in with the current version 1.0 that people are using: should we re-package with that fixed? And what's the best way to document the fixes?

**Comment by bhallen** [comment]
Hm, yeah, I think that this seems like a good cause for us to issue a 1.0.1 bugfix release.

Can we start a list of version changes and put it on our github.io page?

**Comment by mmcauliffe** [comment]
Yes, that would probably be a good idea.  I can do builds tomorrow.

I've merged this fix and some textgrid related fixes that I implemented earlier (allowing for word/phone tiers to be specified, lack of inventory in TextGrids bug, and a segment duplication bug in TextGrids) , a display bug when switching between two spontaneous speech corpora (discourses were not cleared), and the ND bug in  #344, so we can easily make a 1.0.1 release.

So all told, issues that have been resolved in 1.0.1 would be:
#307 
#308 
#313 
#314 
#336
#344

**Comment by kchall** [comment]
Sounds good, thanks, Michael. Is there an easy way for people in the future to, say, sign up to get an alert when a new version is available? (I assume it's too late for the 180 or whatever users currently have it....)

**Comment by mmcauliffe** [comment]
Correct.  We can advertise a new release on all our outlets, but yeah, at the moment once they download it, then there's not much we can do, unless they subscribed to updates on SourceForge (which I assume sends out alerts when new things get posted?)

I've had some success tonight in figuring out how to do the basics of a self updating executable.  So, there would be a menu option "Check for updates...", it would query some website to see what the latest version was, download the new version, install it, and restart itself.  So I can try to get that into the 1.0.1 release for tomorrow, or definitely for 1.1.

**Comment by kchall** [comment]
Cool, that's good to know that SourceForge can do updates -- I hadn't noticed that before, but I signed up for updates, so hopefully we can test it. 

A self-updating executable would be really snazzy. Do you think it would be doable in the next few days? If so, then, yes, let's go ahead and do that for 1.0.1, even if that means delaying over the weekend. If it looks to be more complicated, then let's hold off and get the functional load fix out.

Thanks!

**Comment by kchall** [comment]
Also, can we resolve #334 as well, before we re-package?

**Comment by mmcauliffe** [comment]
Sure, incorporating Blake's suggestion?

**Comment by kchall** [comment]
Yes, that seems like a reasonable disambiguation to me.

**Comment by bhallen** [comment]
This bug became a versioning discussion, but I think everything here is resolved now.
