### ISSUE TITLE
Segment status

### ISSUE THREAD

**Issue by bhallen** [kchall/CorpusTools#337]
I had thought that we changed our corpus architecture so that transcriptions are made of segments which are strings, with their feature accessible by using a segment's string as the key in some feature dictionary. But looking at our corpora's inventory properties now, it looks like they're made up of Segment objects. Is this correct? Did we ultimately decide against foregoing Segments in favor of strings? Or has the function that creates the inventory property just not been updated yet?

**Comment by mmcauliffe** [comment]
So how it works is that transcriptions have lists of strings that correspond to keys in a corpus' inventory.  The values of the inventory are Segment objects, which are primarily wrappers around the feature dictionary (so you can do segment['feature1'] and get the value for 'feature1'), but have some convenience methods for analyzing that feature dictionary as well.  This is how segments can get categories like "Consonant" or "Vowel", place of articulation, vowel height, etc.  So essentially, the inventory stores segment types (Segment objects) and transcriptions store segment tokens (strings that can be looked up in the inventory if necessary).

Does that make sense?

**Comment by bhallen** [comment]
Got it! Makes sense. Thanks!
