### ISSUE TITLE
Tooltip boxes appear black on Ubuntu 14.04

### ISSUE THREAD

**Issue by mmcauliffe** [kchall/CorpusTools#339]
Maybe just an issue with Unity theme?  @bhallen, @mdfry is this an issue with your guys' versions?  I think you're both on Ubuntu (14.04?), Gnome 3, right?

**Comment by bhallen** [comment]
They look great on my machine. Ubuntu 14.04, Gnome 3.10.4

**Comment by mmcauliffe** [comment]
Ah, ok, it looks like it's a Unity bug that affects all Qt applications, so hopefully it gets fixed by Ubuntu devs at some point.
