### ISSUE TITLE
Error thrown if no [tense] feature in inventory

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#348]
With an inventory that didn't use [tense] as a feature, I got the following error:
![tense_inventory](https://cloud.githubusercontent.com/assets/7317450/6428953/c9dce4fa-bf6a-11e4-95e9-b08acd3a443e.jpg)

**Comment by kchall** [comment]
Why are jpgs no longer workign? Also, for some reason I can't copy and paste the error from Idle on my home laptop. The full error is tense_inventory.jpg in the "errors" folder.

**Comment by kchall** [comment]
![image](https://cloud.githubusercontent.com/assets/7317450/6428966/6391e73a-bf6b-11e4-9822-8b27e01c6f76.png)

**Comment by kchall** [comment]
Similar problem happens with [front].

**Comment by mmcauliffe** [comment]
I put a temp fix which will catch those errors (and make it default to bad unstructured layout for segment buttons).  A better fix would be a more dynamic (and user-specifiable) categorization scheme.  I'll have a think about how to implement something like that.

**Comment by kchall** [comment]
The temp fix doesn't seem to cover labiodental, trill, and tap.

**Comment by kchall** [comment]
Grr. I didn't ever switch back to the master from when you were using version 1.0 last week, so my syncs weren't working. Forget I said anything. :)
